WIP
maxorax/Android_Lesson pull request #2
Opened 2020-04-29 09:42 UTC by maxorax

MainActivity - главная и единственная активность в приложении
-- ContactListFragment - фрагмент со списком контактов
---- Короткая карточка контакта
------ Фотография контакта
------ Имя контакта
------ Телефон контакта
При клике пользователя на карточку контакта происходит переход на фрагмент деталей контактов.
-- ContactDetailsFragment
---- Фотография контакта
---- Имя контакта
---- Телефон контакта
---- 2-й телефон
---- e-mail контакта
---- 2-й e-mail контакта
---- Описание контакта

- Кнопка "Назад"  работает - т.е. с деталей контакта мы можем вернуться обратно на список контактов
- У активности  Toolbar с colorPrimary цветом
- каждый фрагмент меняет заголовок в Toolbar: ContactListFragment -> "Список контактов", ContactDetailsFragment -> "Детали контакта"
-colorPrimaryDark сделал равным colorPrimary
получившиеся hex цвета: colorPrimary = #2466bd ,colorAccent = #7864c4

Вроде как почти все сделано, пока не могу разобраться как передавать аргументы.
<img width="442" alt="Снимок экрана 2020-04-29 в 13 41 29" src="https://user-images.githubusercontent.com/37916430/80582118-3cfc2c00-8a1f-11ea-9997-13f73ca1ef2a.png">
<img width="442" alt="Снимок экрана 2020-04-29 в 13 41 34" src="https://user-images.githubusercontent.com/37916430/80582135-41c0e000-8a1f-11ea-9d7c-f253b31d960e.png">

2020-04-29 09:57 UTC, goblinr requested changes
Нужно поправить комментарии и доделать навигацию в приложении
Так же не забудь, что нужно передавать ID выбранного контакта в фрагмент деталей контакта.

2020-04-29 09:57 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/MainActivity.java
> +    Fragment fragment = new ContactListFragment();
Хранить ссылку на `Fragment` не стоит в активности. Это может привести к утечке памяти выделенной под фрагмент

2020-04-29 09:57 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/MainActivity.java
> +        addFragment();
Возможна ситуация, при которой фрагмент добавится несколько раз. Например после поворота экрана.
Нужно защититься от этого так:
```java
if (savedInstanceState == null) {
  // можно делать транзакцию, т.к. мы точно запускаемся в первый раз
}
```

2020-04-29 09:57 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
`FrameLayout` - явно не подходит в качестве контейнера для этого экрана. Посмотри в сторону `ConstraintLayout` либо комбинации из вложенных контейнеров разных типов.

2020-04-29 09:57 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:layout_marginEnd="10dp"
Верстать таким образом - неверно. Нужно стремиться к резиновой верстке, поэтому лучше оперировать `match_parent` и `wrap_content` для android:layout_width и android:layout_height
Это касается всего проекта

2020-04-29 09:57 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Здесь то же самое

2020-04-29 09:57 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <FrameLayout
Бессмысленная вложенность контейнеров

2020-04-29 13:08 UTC, maxorax commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <FrameLayout
А что можно использовать для короткой карточки, вместо короткой карточки?

2020-04-29 16:08 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <FrameLayout
Не заметил, что ты используешь его в качестве фона. Теоретически, можно фон добавить верхнему контейнеру и задать ему отступы

2020-04-29 22:34 UTC, maxorax commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <FrameLayout
У меня к этому контейнеру привязан onClick, если его уберу, то мне к фотке привязать?

2020-04-30 04:00 UTC, goblinr requested changes

2020-04-30 04:00 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:layout_height="wrap_content"
Для фото лучше оставить жесткие размеры

2020-04-30 04:00 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +        android:paddingLeft="7dp"
нечетные размеры.
Это нужно поправить везде

2020-04-30 04:00 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <FrameLayout
Зачем? Ты можешь привязать клик к любому View,  включая верхний контейнер

2020-04-30 04:00 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +            android:layout_height="wrap_content"
Нужно оставить жесткие размеры для картинки

2020-04-30 04:00 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <FrameLayout
Бессмысленная вложенность осталась. Нужно избавиться от этой вложенности

2020-05-01 02:06 UTC, maxorax reviewed
Поправил комментарии, смог разобраться с bundle и теперь передаю ID через аргументы

2020-05-01 09:45 UTC, goblinr requested changes

2020-05-01 09:45 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactDetailsFragment.java
> +    private TextView description;
Все ссылки на View следует обнулять в `onDestroyView()`

2020-05-01 09:45 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +    private TextView phone;
Ссылки на  view следует обнулять в onDestroyView()

2020-05-01 09:45 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +    public static ContactListFragment newInstance(Contact contact){
`ContactListFragment`у не нужно передавать аргументы по условиям ДЗ

2020-05-01 09:45 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/pojo/Contact.java
> +    private String description;
`final` ко всем  полям

2020-05-01 09:45 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/pojo/ContactList.java
> +public class ContactList {
А этот класс зачем? Он нигде не используется.
Нужно удалить.

2020-05-01 09:45 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +
Много пустых строк

2020-05-01 09:45 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_details.xml
> +
Много пустых строк

2020-05-01 09:45 UTC, goblinr commented on app/src/main/res/layout/activity_main.xml
> +</LinearLayout>
Много пустых строк

2020-05-01 09:45 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:onClick="onClickOnContact"
Не делай так.
устанавливай ClickListener в Java коде

2020-05-01 09:45 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +
Много пустых строк

2020-05-01 09:45 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +    <androidx.cardview.widget.CardView
Не верное решение, должно быть так:
```xml
<androidx.cardview.widget.CardView ...>
    <androidx.constraintlayout.widget.ConstraintLayout ...>
           ...
    </androidx.constraintlayout.widget.ConstraintLayout>
</androidx.cardview.widget.CardView>
```

2020-05-02 17:29 UTC, goblinr requested changes

2020-05-02 17:29 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +    catch (ClassCastException e){}
Пустой блок  `catch` - так делать нельзя.

2020-05-02 17:29 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +        ((ContactClick)getActivity()).onClickOnContact(getActivity().findViewById(R.id.contactCard));
Лучше сделай как я рассказывал в лекции - проверь оператором `instanceof` в `onAttach` удовлетворяет ли активность к которой присоединяется фрагмент, интерфейсу `ContactClick` и сохрани в поле. Не забудь обнулить в `onDetach`

2020-05-02 17:29 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +public class ContactListFragment extends Fragment implements View.OnClickListener{
Фрагмент реализует интерфейс `View.OnClickListener`, но не устанавливается в качестве слушателя ни одной View

2020-05-02 17:29 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +        onClick(view);
Это абсолютно не понятно. Тому кто прочитает данный код - будет казаться, что здесь вызывается метод обратного вызова `onClick`, хотя на самом деле это не так.

2020-05-02 17:29 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/MainActivity.java
> +    public void onClickOnContact(View view) {
Зачем передавать View в качестве параметра, когда можно сразу передать ID выбранного контакта?

2020-05-02 17:29 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/pojo/Contact.java
> +    private final String DESCRIPTION;
Названия полей - как у констант, хотя по факту - они не константы.

2020-05-03 03:43 UTC, goblinr requested changes

2020-05-03 03:43 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +    private Context activity = null;
`private ContactClick contactClick = null;`

2020-05-03 03:43 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +            activity = context;
`contacktClick = (ContactClick) context;`

2020-05-03 03:43 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +    private void Click() {
Название метода не соответствует тому, что в нем происходит.

2020-05-03 03:43 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +    private void Click() {
+ название метода с заглавной буквы - не принято в  Java

2020-05-03 03:43 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/MainActivity.java
> +        findViewById(id).setOnClickListener(new View.OnClickListener() {
Это полный бред. `setOnClickListener` нужно делать внутри `ContactListFragment` а сюда уже передавать ID  выбранного контакта

2020-05-03 11:11 UTC, goblinr requested changes

2020-05-03 11:11 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +    private Contact contact;
Сделай этот контакт константой

2020-05-03 11:11 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +             catch (ClassCastException e){
Зачем отлавливать здесь `ClassCastException`?

2020-05-03 11:11 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/MainActivity.java
> +                transaction.replace(R.id.fragments_container, contactDetails).addToBackStack(null).commit();
Много табуляций

2020-05-03 11:11 UTC, goblinr commented on app/src/main/java/android/develop/a65apps/maxim/orlov/ContactListFragment.java
> +             catch (ClassCastException e){
Нужно проверить `contactClick` на `null` прежде чем вызывать на нем метод

2020-05-03 12:09 UTC, goblinr approved these changes
Обнови скриншоты
До-оформи PR
И можно мержить

2020-05-03 12:37 UTC, merged